AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    voice-to-text

Parameters:
    AppBucketName:
        Type: String
        Description: "REQUIRED: Unique S3 bucket name to use for the app."
    AssemblyAIApiKey:
        Type: String
        Description: "REQUIRED: Assembly AI API Key."
    AssemblyWebhookAccessKey:
        Type: String
        Description: "REQUIRED: Symfony App Assembly Webhook Access Key."
    LambdaWebhookAccessKey:
        Type: String
        Description: "REQUIRED: Symfony App Lambda Webhook Access Key."
    SymfonyAppUrl:
        Type: String
        Description: "REQUIRED: Symfony App Public URL (ngrok?)."

Resources:
    S3VoiceToTextFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/s3-voice-to-text.handler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            MemorySize: 128
            Timeout: 10
            Policies:
                S3ReadPolicy:
                    BucketName: !Ref AppBucketName
            Events:
                S3NewObjectEvent:
                    Type: S3
                    Properties:
                        Bucket: !Ref AppBucket
                        Events: s3:ObjectCreated:*
                        # Filter:
                        #   S3Key:
                        #     Rules:
                        #       - Name: suffix
                        #         Value: ".wav"
            Environment:
                Variables:
                    ASSEMBLY_AI_API_KEY: !Ref AssemblyAIApiKey
                    ASSEMBLY_WEBHOOK_ACCESS_KEY: !Ref AssemblyWebhookAccessKey
                    LAMBDA_WEBHOOK_ACCESS_KEY: !Ref LambdaWebhookAccessKey
                    SYMFONY_APP_URL: !Ref SymfonyAppUrl
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                # EntryPoints:
                # - app.ts
    AppBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref AppBucketName
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - BucketKeyEnabled: true
            VersioningConfiguration:
                Status: Enabled
